schema:
    - ./config/schema.graphql
generates:
    pkg/types/entities.go:
      config:
        packageName: types
        # entities:
        #   - Workspace
        #   - Schema
        #   - Table
        #   - Column